dom(_, czerwony, anglik, _, _, _).
dom(_, _, hiszpan, pies, _, _).
dom(_, zielony, _, _, _, kawa).
dom(_, _, ukrainiec, _, _, herbata).
dom(_, _, _, wąż, winstony, _).
dom(_, żółty, _, _, koole, _).
dom(3, _, _, _, _, mleko).
dom(1, _, norweg, _, _, _).
dom(_, _, _, _, luckyStrike, sok).
dom(_, _, japończyk, _, kenty, _).
